/**
 * Common-Cents - Backend Server
 * Auto-generated by Module Library Assembler
 * 
 * Run: npm install && npm run dev
 */

const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
require('dotenv').config();

const app = express();

// ============================================
// MIDDLEWARE
// ============================================

app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors({ origin: true, credentials: true }));
app.use(morgan('dev'));
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: true, limit: '50mb' }));

// ============================================
// MODULE ROUTES (Auto-Wired)
// ============================================

const authRoutes = require('./modules/auth/routes/auth.js');
const surveysRoutes = require('./modules/surveys/routes/surveys.js');
const streaksRoutes = require('./modules/streaks/routes/streaks.js');
const daily_spinRoutes = require('./modules/daily-spin/routes/spin.js');
const achievementsRoutes = require('./modules/achievements/routes/achievements.js');
const user_balanceRoutes = require('./modules/user-balance/routes/balance.js');
const cashoutsRoutes = require('./modules/cashouts/routes/cashouts.js');
const notificationsRoutes = require('./modules/notifications/routes/notifications.js');
const analyticsRoutes = require('./modules/analytics/routes/metrics.js');
const fraud_detectionRoutes = require('./modules/fraud-detection/routes/fraud.js');
const payout_verificationRoutes = require('./modules/payout-verification/routes/verification.js');
const onboardingRoutes = require('./modules/onboarding/routes/onboarding.js');

// Register routes
app.use('/api/auth', authRoutes);
app.use('/api/surveys', surveysRoutes);
app.use('/api/streaks', streaksRoutes);
app.use('/api/spin', daily_spinRoutes);
app.use('/api/achievements', achievementsRoutes);
app.use('/api/balance', user_balanceRoutes);
app.use('/api/cashouts', cashoutsRoutes);
app.use('/api/notifications', notificationsRoutes);
app.use('/api/analytics', analyticsRoutes);
app.use('/api/fraud-detection', fraud_detectionRoutes);
app.use('/api/payout-verification', payout_verificationRoutes);
app.use('/api/onboarding', onboardingRoutes);

// ============================================
// BRAIN & HEALTH ROUTES (Admin System)
// ============================================

const brainRoutes = require('./routes/brain');
const healthRoutes = require('./routes/health');

app.use('/api/brain', brainRoutes);
app.use('/api/health', healthRoutes);

// ============================================
// ADMIN CRUD ROUTES
// ============================================

const customersRoutes = require('./routes/customers');
const productsRoutes = require('./routes/products');
const ordersRoutes = require('./routes/orders');
const competitorsRoutes = require('./routes/competitors');

app.use('/api/customers', customersRoutes);
app.use('/api/products', productsRoutes);
app.use('/api/orders', ordersRoutes);
app.use('/api/competitors', competitorsRoutes);

// Quick health check (legacy)
app.get('/health', (req, res) => {
  res.json({
    status: 'ok',
    project: 'Common-Cents',
    timestamp: new Date().toISOString(),
    modules: 16
  });
});

// ============================================
// ERROR HANDLING
// ============================================

app.use((err, req, res, next) => {
  console.error('Error:', err.message);
  res.status(err.status || 500).json({
    error: err.message || 'Internal server error'
  });
});

// 404 handler
app.use((req, res) => {
  res.status(404).json({ error: 'Not found', path: req.path });
});

// ============================================
// START SERVER
// ============================================

const PORT = process.env.PORT || 5000;

app.listen(PORT, () => {
  console.log('');
  console.log('🚀 Common-Cents backend running on port ' + PORT);
  console.log('   Health: http://localhost:' + PORT + '/health');
  console.log('   API:    http://localhost:' + PORT + '/api');
  console.log('');
  console.log('📦 Loaded modules (16):');
  console.log('   ✅ auth');
  console.log('   ✅ surveys');
  console.log('   ✅ streaks');
  console.log('   ✅ daily-spin');
  console.log('   ✅ achievements');
  console.log('   ✅ user-balance');
  console.log('   ✅ cashouts');
  console.log('   ✅ notifications');
  console.log('   ✅ analytics');
  console.log('   ✅ fraud-detection');
  console.log('   ✅ payout-verification');
  console.log('   ✅ onboarding');
  console.log('   ✅ customers (admin)');
  console.log('   ✅ products (admin)');
  console.log('   ✅ orders (admin)');
  console.log('   ✅ competitors (admin)');
});

module.exports = app;
