/**
 * Database Setup Script
 * Auto-generated by Module Library Assembler
 * 
 * Run: node setup-db.js
 * This will create all required tables if they don't exist
 */

require('dotenv').config();
const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false
});

const tables = {
  // Users table (auth module)
  users: `
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      email VARCHAR(255) UNIQUE NOT NULL,
      password_hash VARCHAR(255) NOT NULL,
      full_name VARCHAR(255),
      phone VARCHAR(50),
      subscription_tier VARCHAR(50) DEFAULT 'free',
      is_admin BOOLEAN DEFAULT false,
      scans_used INTEGER DEFAULT 0,
      referred_by VARCHAR(50),
      referral_code_id INTEGER,
      referred_at TIMESTAMP,
      reset_token VARCHAR(255),
      reset_token_expires TIMESTAMP,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,
  
  // Bookings table (booking module)
  bookings: `
    CREATE TABLE IF NOT EXISTS bookings (
      id SERIAL PRIMARY KEY,
      user_id INTEGER REFERENCES users(id),
      customer_name VARCHAR(255) NOT NULL,
      customer_email VARCHAR(255),
      customer_phone VARCHAR(50),
      service_type VARCHAR(100) DEFAULT 'general',
      booking_date DATE NOT NULL,
      start_time TIME NOT NULL,
      end_time TIME,
      party_size INTEGER DEFAULT 1,
      notes TEXT,
      status VARCHAR(50) DEFAULT 'pending',
      cancellation_reason TEXT,
      cancelled_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,
  
  // Contact submissions
  contact_submissions: `
    CREATE TABLE IF NOT EXISTS contact_submissions (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL,
      phone VARCHAR(50),
      subject VARCHAR(255),
      message TEXT NOT NULL,
      status VARCHAR(50) DEFAULT 'new',
      responded_at TIMESTAMP,
      created_at TIMESTAMP DEFAULT NOW()
    )
  `,
  
  // Referral codes (auth module)
  referral_codes: `
    CREATE TABLE IF NOT EXISTS referral_codes (
      id SERIAL PRIMARY KEY,
      code VARCHAR(50) UNIQUE NOT NULL,
      user_id INTEGER REFERENCES users(id),
      total_signups INTEGER DEFAULT 0,
      active BOOLEAN DEFAULT true,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,
  
  // Services/Products
  services: `
    CREATE TABLE IF NOT EXISTS services (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      description TEXT,
      price DECIMAL(10, 2),
      duration_minutes INTEGER,
      category VARCHAR(100),
      active BOOLEAN DEFAULT true,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,
  
  // Reviews/Testimonials
  reviews: `
    CREATE TABLE IF NOT EXISTS reviews (
      id SERIAL PRIMARY KEY,
      user_id INTEGER REFERENCES users(id),
      booking_id INTEGER REFERENCES bookings(id),
      rating INTEGER CHECK (rating >= 1 AND rating <= 5),
      title VARCHAR(255),
      content TEXT,
      approved BOOLEAN DEFAULT false,
      created_at TIMESTAMP DEFAULT NOW()
    )
  `,
  
  // Newsletter subscribers
  subscribers: `
    CREATE TABLE IF NOT EXISTS subscribers (
      id SERIAL PRIMARY KEY,
      email VARCHAR(255) UNIQUE NOT NULL,
      name VARCHAR(255),
      subscribed BOOLEAN DEFAULT true,
      created_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Customers table (admin module)
  customers: `
    CREATE TABLE IF NOT EXISTS customers (
      id SERIAL PRIMARY KEY,
      user_id INTEGER REFERENCES users(id),
      name VARCHAR(255) NOT NULL,
      email VARCHAR(255) UNIQUE NOT NULL,
      phone VARCHAR(50),
      total_spent DECIMAL(10, 2) DEFAULT 0,
      order_count INTEGER DEFAULT 0,
      lifetime_value DECIMAL(10, 2) DEFAULT 0,
      segment VARCHAR(50) DEFAULT 'new',
      notes TEXT,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Products table (admin module)
  products: `
    CREATE TABLE IF NOT EXISTS products (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      description TEXT,
      price DECIMAL(10, 2) NOT NULL,
      category VARCHAR(100),
      inventory_count INTEGER DEFAULT 0,
      sku VARCHAR(100),
      active BOOLEAN DEFAULT true,
      image_url TEXT,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Orders table (admin module)
  orders: `
    CREATE TABLE IF NOT EXISTS orders (
      id SERIAL PRIMARY KEY,
      customer_id INTEGER REFERENCES customers(id),
      order_number VARCHAR(50) UNIQUE NOT NULL,
      total DECIMAL(10, 2) NOT NULL,
      subtotal DECIMAL(10, 2),
      tax DECIMAL(10, 2) DEFAULT 0,
      status VARCHAR(50) DEFAULT 'pending',
      payment_status VARCHAR(50) DEFAULT 'unpaid',
      payment_method VARCHAR(50),
      notes TEXT,
      shipping_address TEXT,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Order items table (admin module)
  order_items: `
    CREATE TABLE IF NOT EXISTS order_items (
      id SERIAL PRIMARY KEY,
      order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
      product_id INTEGER REFERENCES products(id),
      product_name VARCHAR(255) NOT NULL,
      quantity INTEGER NOT NULL DEFAULT 1,
      unit_price DECIMAL(10, 2) NOT NULL,
      total_price DECIMAL(10, 2) NOT NULL,
      created_at TIMESTAMP DEFAULT NOW()
    )
  `,

  // Competitors table (admin module)
  competitors: `
    CREATE TABLE IF NOT EXISTS competitors (
      id SERIAL PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      website VARCHAR(255),
      distance DECIMAL(5, 2),
      type VARCHAR(100) DEFAULT 'Direct Competitor',
      threat_level VARCHAR(50) DEFAULT 'medium',
      rating DECIMAL(3, 2),
      rating_change DECIMAL(3, 2) DEFAULT 0,
      review_count INTEGER DEFAULT 0,
      avg_price DECIMAL(10, 2),
      price_diff INTEGER DEFAULT 0,
      strengths TEXT[],
      weaknesses TEXT[],
      top_items JSONB,
      sentiment JSONB,
      last_analyzed TIMESTAMP,
      notes TEXT,
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `
};

async function setupDatabase() {
  console.log('🗄️  Setting up database...\n');

  try {
    // Test connection
    await pool.query('SELECT NOW()');
    console.log('✅ Database connected\n');

    // Create each table
    for (const [tableName, createSQL] of Object.entries(tables)) {
      try {
        await pool.query(createSQL);
        console.log(`✅ Table "${tableName}" ready`);
      } catch (err) {
        console.error(`❌ Failed to create "${tableName}":`, err.message);
      }
    }

    // Create indexes for performance
    console.log('\n📊 Creating indexes...');

    const indexes = [
      'CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)',
      'CREATE INDEX IF NOT EXISTS idx_bookings_date ON bookings(booking_date)',
      'CREATE INDEX IF NOT EXISTS idx_bookings_user ON bookings(user_id)',
      'CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status)',
      'CREATE INDEX IF NOT EXISTS idx_contact_status ON contact_submissions(status)',
      // Admin module indexes
      'CREATE INDEX IF NOT EXISTS idx_customers_email ON customers(email)',
      'CREATE INDEX IF NOT EXISTS idx_customers_segment ON customers(segment)',
      'CREATE INDEX IF NOT EXISTS idx_products_category ON products(category)',
      'CREATE INDEX IF NOT EXISTS idx_products_active ON products(active)',
      'CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id)',
      'CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status)',
      'CREATE INDEX IF NOT EXISTS idx_orders_created ON orders(created_at)',
      'CREATE INDEX IF NOT EXISTS idx_competitors_threat ON competitors(threat_level)'
    ];

    for (const idx of indexes) {
      try {
        await pool.query(idx);
      } catch (err) {
        // Index might already exist, that's fine
      }
    }
    console.log('✅ Indexes created\n');

    // Seed admin user if ADMIN_EMAIL and ADMIN_PASSWORD are set
    await seedAdminUser();

    // Seed demo data if SEED_DEMO_DATA=true
    await seedDemoData();

    // Summary
    const tableCount = await pool.query(`
      SELECT COUNT(*) FROM information_schema.tables
      WHERE table_schema = 'public'
    `);

    console.log('═══════════════════════════════════════');
    console.log(`✅ Database setup complete!`);
    console.log(`   Tables: ${tableCount.rows[0].count}`);
    console.log('═══════════════════════════════════════\n');

  } catch (error) {
    console.error('❌ Database setup failed:', error.message);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

/**
 * Seed admin user from environment variables
 * Only creates if ADMIN_EMAIL and ADMIN_PASSWORD are set
 */
async function seedAdminUser() {
  const adminEmail = process.env.ADMIN_EMAIL;
  const adminPassword = process.env.ADMIN_PASSWORD;

  if (!adminEmail || !adminPassword) {
    console.log('⚠️  ADMIN_EMAIL/ADMIN_PASSWORD not set - skipping admin seeding');
    return;
  }

  console.log('\n👤 Seeding admin user...');

  try {
    // Check if admin already exists
    const existingResult = await pool.query(
      'SELECT id FROM users WHERE email = $1',
      [adminEmail]
    );

    if (existingResult.rows.length > 0) {
      // Update existing admin password
      const bcrypt = require('bcryptjs');
      const passwordHash = await bcrypt.hash(adminPassword, 10);

      await pool.query(
        'UPDATE users SET password_hash = $1, is_admin = true, updated_at = NOW() WHERE email = $2',
        [passwordHash, adminEmail]
      );
      console.log(`✅ Admin user updated: ${adminEmail}`);
    } else {
      // Create new admin user
      const bcrypt = require('bcryptjs');
      const passwordHash = await bcrypt.hash(adminPassword, 10);

      await pool.query(
        `INSERT INTO users (email, password_hash, full_name, is_admin, subscription_tier, created_at, updated_at)
         VALUES ($1, $2, $3, true, 'admin', NOW(), NOW())`,
        [adminEmail, passwordHash, 'Admin']
      );
      console.log(`✅ Admin user created: ${adminEmail}`);
    }
  } catch (err) {
    console.error('⚠️  Could not seed admin user:', err.message);
  }
}

/**
 * Seed demo data for admin dashboard
 * Only seeds if SEED_DEMO_DATA=true
 */
async function seedDemoData() {
  if (process.env.SEED_DEMO_DATA !== 'true') {
    console.log('⚠️  SEED_DEMO_DATA not set to true - skipping demo data');
    return;
  }

  console.log('\n🌱 Seeding demo data...');

  try {
    // Check if demo data already exists
    const existingCompetitors = await pool.query('SELECT COUNT(*) FROM competitors');
    if (parseInt(existingCompetitors.rows[0].count) > 0) {
      console.log('   Demo data already exists, skipping...');
      return;
    }

    // Seed competitors
    const competitors = [
      {
        name: "Joe's Diner",
        website: 'https://joesdiner.example.com',
        distance: 0.3,
        type: 'Direct Competitor',
        threat_level: 'medium',
        rating: 4.2,
        rating_change: -0.1,
        review_count: 342,
        avg_price: 14.99,
        price_diff: -13,
        strengths: ['Large portions', 'Fast service', 'Parking'],
        weaknesses: ['Dated decor', 'Limited vegetarian options'],
        top_items: [
          { name: 'Classic Burger', price: 15.99 },
          { name: 'Chicken Wings', price: 12.99 }
        ],
        sentiment: { positive: 65, neutral: 25, negative: 10 }
      },
      {
        name: 'Main Street Cafe',
        website: 'https://mainstreetcafe.example.com',
        distance: 0.5,
        type: 'Direct Competitor',
        threat_level: 'high',
        rating: 4.4,
        rating_change: 0.2,
        review_count: 521,
        avg_price: 13.49,
        price_diff: -4,
        strengths: ['Modern atmosphere', 'Strong social media', 'Loyalty program'],
        weaknesses: ['Slow during rush', 'Higher prices'],
        top_items: [
          { name: 'Avocado Toast', price: 11.99 },
          { name: 'House Burger', price: 14.49 }
        ],
        sentiment: { positive: 78, neutral: 15, negative: 7 }
      },
      {
        name: 'Corner Bistro',
        website: 'https://cornerbistro.example.com',
        distance: 0.8,
        type: 'Indirect Competitor',
        threat_level: 'low',
        rating: 4.6,
        rating_change: 0,
        review_count: 189,
        avg_price: 24.99,
        price_diff: -48,
        strengths: ['Upscale dining', 'Wine selection', 'Date night destination'],
        weaknesses: ['High prices', 'Long wait times', 'Limited parking'],
        top_items: [
          { name: 'Filet Mignon', price: 38.99 },
          { name: 'Truffle Pasta', price: 28.99 }
        ],
        sentiment: { positive: 82, neutral: 12, negative: 6 }
      }
    ];

    for (const c of competitors) {
      await pool.query(
        `INSERT INTO competitors (name, website, distance, type, threat_level, rating, rating_change, review_count, avg_price, price_diff, strengths, weaknesses, top_items, sentiment, created_at, updated_at)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, NOW(), NOW())`,
        [c.name, c.website, c.distance, c.type, c.threat_level, c.rating, c.rating_change, c.review_count, c.avg_price, c.price_diff, c.strengths, c.weaknesses, JSON.stringify(c.top_items), JSON.stringify(c.sentiment)]
      );
    }
    console.log('   ✅ Competitors seeded');

    // Seed products
    const products = [
      { name: 'Survey Completion Bonus', description: 'Reward for completing surveys', price: 2.50, category: 'Rewards', inventory_count: 9999, sku: 'RWD-001' },
      { name: 'Daily Streak Bonus', description: 'Bonus for daily login streaks', price: 0.50, category: 'Bonuses', inventory_count: 9999, sku: 'BNS-001' },
      { name: 'Spin Wheel Prize', description: 'Random spin wheel reward', price: 5.00, category: 'Bonuses', inventory_count: 9999, sku: 'BNS-002' },
      { name: 'Referral Bonus', description: 'Reward for referring friends', price: 3.00, category: 'Referrals', inventory_count: 9999, sku: 'REF-001' },
      { name: 'Premium Survey', description: 'Higher paying survey opportunity', price: 10.00, category: 'Rewards', inventory_count: 100, sku: 'RWD-002' }
    ];

    for (const p of products) {
      await pool.query(
        `INSERT INTO products (name, description, price, category, inventory_count, sku, active, created_at, updated_at)
         VALUES ($1, $2, $3, $4, $5, $6, true, NOW(), NOW())`,
        [p.name, p.description, p.price, p.category, p.inventory_count, p.sku]
      );
    }
    console.log('   ✅ Products seeded');

    // Seed customers
    const customers = [
      { name: 'John Smith', email: 'john.smith@example.com', phone: '555-0101', total_spent: 125.50, order_count: 12, segment: 'active' },
      { name: 'Sarah Johnson', email: 'sarah.j@example.com', phone: '555-0102', total_spent: 89.25, order_count: 8, segment: 'active' },
      { name: 'Mike Williams', email: 'mike.w@example.com', phone: '555-0103', total_spent: 45.00, order_count: 5, segment: 'new' },
      { name: 'Emily Brown', email: 'emily.b@example.com', phone: '555-0104', total_spent: 230.75, order_count: 25, segment: 'vip' },
      { name: 'David Lee', email: 'david.lee@example.com', phone: '555-0105', total_spent: 15.00, order_count: 2, segment: 'new' }
    ];

    const customerIds = [];
    for (const c of customers) {
      const result = await pool.query(
        `INSERT INTO customers (name, email, phone, total_spent, order_count, segment, created_at, updated_at)
         VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW()) RETURNING id`,
        [c.name, c.email, c.phone, c.total_spent, c.order_count, c.segment]
      );
      customerIds.push(result.rows[0].id);
    }
    console.log('   ✅ Customers seeded');

    // Seed a few sample orders
    const orders = [
      { customer_idx: 0, order_number: 'ORD-DEMO-001', total: 25.00, status: 'completed', payment_status: 'paid' },
      { customer_idx: 1, order_number: 'ORD-DEMO-002', total: 15.50, status: 'completed', payment_status: 'paid' },
      { customer_idx: 3, order_number: 'ORD-DEMO-003', total: 50.00, status: 'pending', payment_status: 'unpaid' },
      { customer_idx: 2, order_number: 'ORD-DEMO-004', total: 10.00, status: 'processing', payment_status: 'paid' }
    ];

    for (const o of orders) {
      await pool.query(
        `INSERT INTO orders (customer_id, order_number, total, subtotal, tax, status, payment_status, created_at, updated_at)
         VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())`,
        [customerIds[o.customer_idx], o.order_number, o.total, o.total * 0.92, o.total * 0.08, o.status, o.payment_status]
      );
    }
    console.log('   ✅ Orders seeded');

    console.log('✅ Demo data seeding complete!');
  } catch (err) {
    console.error('⚠️  Could not seed demo data:', err.message);
  }
}

// Run setup
setupDatabase();